### ISSUE TITLE
Error: list indexes must be integers or slides, not strings

### ISSUE THREAD

**Issue by matthijsmelissen** [luka1199/geo-heatmap#24]
I get the following error message when running this script:
```Loading data from /Users/User/Downloads/Takeout/Location History/Location History.kml...
|##############################################################################################################################|100% ETA:  00:00:00
Traceback (most recent call last):
  File "geo_heatmap.py", line 222, in <module>
    generator.run(data_file, output_file, date_range)
  File "geo_heatmap.py", line 177, in run
    self.loadKMLData(data_file, date_range)
  File "geo_heatmap.py", line 93, in loadKMLData
    if self.timestampInRange(loc['timestampMs'], date_range):
TypeError: list indices must be integers or slices, not str
```

Input KML file:
```<?xml version='1.0' encoding='UTF-8'?>
<kml xmlns='http://www.opengis.net/kml/2.2' xmlns:gx='http://www.google.com/kml/ext/2.2'>
 <Document>
  <Placemark>
   <open>1</open>
   <gx:Track>
    <altitudeMode>clampToGround</altitudeMode>
    <when>2013-12-22T11:38:47Z</when>
    <gx:coord>-1.1 52.1 0</gx:coord>
   </gx:Track>
  </Placemark>
 </Document>
</kml>
```

Any idea what might cause this?

**Comment by luka1199** [comment]
Can you run `git pull` in the folder? Or just redownload the project. This got fixed after you downloaded it

**Comment by matthijsmelissen** [comment]
This fixes it, thanks! Nice tool!
