### ISSUE TITLE
Script not compatible with the latest Takeout zip structure

### ISSUE THREAD

**Issue by davidmigloz** [luka1199/geo-heatmap#58]
I downloaded my location data today and tried to run the script but I'm getting the following exception:
```
python geo_heatmap.py takeout-20230101T215713Z-001.zip

(1/3) Loading data from takeout-20230101T215713Z-001.zip
Traceback (most recent call last):
  File "/Users/davidmigloz/repos/geo-heatmap/geo_heatmap.py", line 327, in <module>
    generator.run(data_file, output_file, date_range, stream_data, settings)
  File "/Users/davidmigloz/repos/geo-heatmap/geo_heatmap.py", line 252, in run
    self.loadZIPData(data_file, date_range)
  File "/Users/davidmigloz/repos/geo-heatmap/geo_heatmap.py", line 173, in loadZIPData
    (data_path,) = fnmatch.filter(
ValueError: not enough values to unpack (expected 1, got 0)
```

The Takeout folder structure doesn't seem to match the one the script is expecting:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/6546265/210186388-8a16d3e4-c8dc-49de-aa60-bec8bb0b1d73.png">

https://github.com/luka1199/geo-heatmap/blob/fc253685d8f918eafbc7e5f47d2257f69873202a/geo_heatmap.py#L175

**Comment by luka1199** [comment]
Looks like Google changed the format again. While this is not fixed you can just unzip the Records.json file and use that (if you haven't already). I'm not sure when I'll have time to fix this issue.

**Comment by mahendra-shah** [comment]
Hi @luka1199 ,

I came across the issue about the Google Takeout format changes and noticed the repository hasn’t been very active recently.

I’m interested in contributing a fix for the updated Takeout structure (handling the newer Semantic Location History format and multi-file inputs). Before I start working on it, I wanted to check if you’re open to external contributions and if there are any guidelines or expectations I should follow.

Happy to put together a PR once I align with your direction.
