### ISSUE TITLE
Data format not recognised when exporting data after migration

### ISSUE THREAD

**Issue by Eliiia** [luka1199/geo-heatmap#61]
Hi, I apologise if this has been brought up before but I could not find an open or closed issue relating to this, nor any instructions in your README. Please let me know if you need any more info. Sorry again if this should be submitted as a feature request instead.

**Describe the bug**
[By 8th December, users will have to have migrated their data to their local device](https://www.reddit.com/r/GoogleMaps/comments/1diivt3/megathread_google_maps_timeline_moving_to/). I found a way to download the data (Android settings -> Location -> Location Services -> Timeline -> Export Timeline Data) after Google recently forced me to migrate, but the script failed to interpret this file. It is a JSON file of a similar format to Records.json.

**To Reproduce**
1. Migrate timeline data to local device
2. Download data through Android settings -> Location -> Location Services -> Timeline -> Export Timeline Data
3. Attempt to use the Timeline.json generated on the script

```
(1/3) Loading data from .\Timeline.json
Traceback (most recent call last):
  File "C:\Users\LLR User\Downloads\geo-heatmap\geo_heatmap.py", line 327, in <module>
    generator.run(data_file, output_file, date_range, stream_data, settings)
  File "C:\Users\LLR User\Downloads\geo-heatmap\geo_heatmap.py", line 258, in run
    self.loadJSONData(json_file, date_range)
  File "C:\Users\LLR User\Downloads\geo-heatmap\geo_heatmap.py", line 57, in loadJSONData
    first_element = data["locations"][0]
                    ~~~~^^^^^^^^^^^^^
KeyError: 'locations'```

**Expected behavior**
The file loads in.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A

 - Android version, if relevant: 14

Also, thank you so much for all your work on the project. This is by far my favourite open source project.

**Comment by Speculate7348** [comment]
I have this problem as well. Hopefully this will get fixed.

**Comment by burggraaff** [comment]
Hi, I was a bit worried about this recent timeline change so thank you very much for pointing out that method for exporting data from Android. I'm not sure if @luka1199 is still maintaining this repository. I'll have a go at fixing this myself because I'm really keen on this programme.

**Comment by Speculate7348** [comment]
> Hi, I was a bit worried about this recent timeline change so thank you very much for pointing out that method for exporting data from Android. I'm not sure if @luka1199 is still maintaining this repository. I'll have a go at fixing this myself because I'm really keen on this programme.

Hi, I haven't looked into the new format. Is it documented anywhere? I agree that this program and its functionality should be updated to a working state again, but I don't know how the new format looks like.

**Comment by martinbros** [comment]
I've opened a Pull Request with my quick fix to the JSON change in formatting. Hopefully it can help someone here in this thread.
